### ISSUE TITLE
python 3.12 breaks importer

### ISSUE THREAD

**Issue by lod** [atsb/nose-py3#13]
The imp library has long been deprecated (since 3.4) and is removed in 3.12.

This is heavily used by nose/importer.py

The replacement importlib works differently so it isn't an easy swap/upgrade.

**Comment by lod** [comment]
I tried my hand at fixing it in https://github.com/lod/nose-py3/pull/new/python-3.12 but didn't have much luck, it's no longer a requirement for me so I won't be pursuing it further..

I think my main problem was a combination of not understanding what the importer code was trying to achieve and not understanding enough of the deep dark workings of the python import process.  The two lack of understandings are probably intertwined.

**Comment by atsb** [comment]
Thanks, I'll take a look at this!

**Comment by atsb** [comment]
I've added a PR which replaces imp with importlib wrapper functions

**Comment by atsb** [comment]
Still a few more cleanups for 3.12 to do but it looks very promising.  pkg_resource is also removed now.  I'll just test a few things and fix some more unit tests and do another official release.

I appreciate the feedback!
