### ISSUE TITLE
nose-py3 cannot be installed from pypi due to logging dependency

### ISSUE THREAD

**Issue by obriencj** [atsb/nose-py3#15]
The explicit 'logging' dependency added in 1.6.4 causes the pypi version of logging to be installed. This version of logging is an old python 2 package, which breaks under installation. eg:

```
Collecting logging (from nose-py3)
  Using cached logging-0.4.9.6.tar.gz (96 kB)
  Preparing metadata (setup.py) ... error

  Running command git clone --filter=blob:none --quiet https://pagure.io/koji.git /tmp/pip-req-build-my62kbdx
  warning: filtering not recognized by server, ignoring
  warning: filtering not recognized by server, ignoring
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/siege/Devel/koji-smoky-dingo/.tox/koji-git/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
        File "/home/siege/Devel/koji-smoky-dingo/.tox/koji-git/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/home/siege/Devel/koji-smoky-dingo/.tox/koji-git/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 70, in do_override
          ensure_local_distutils()
        File "/home/siege/Devel/koji-smoky-dingo/.tox/koji-git/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 56, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
        File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "/home/siege/Devel/koji-smoky-dingo/.tox/koji-git/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 13, in <module>
          from .cmd import Command
        File "/home/siege/Devel/koji-smoky-dingo/.tox/koji-git/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 7, in <module>
          import logging
        File "/tmp/pip-install-fzhk4koi/logging_9ae69de5ee904824a5d03ee85a722a7c/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]
```

**Comment by obriencj** [comment]
Note, this likely only occurs in tox envs created where `site-packages = False` which is probably how it wasn't noticed as broken originally.

the version of logging installed when 'logging' is an explicit dependency (and we're not copying site packages) is from https://pypi.org/project/logging

**Comment by obriencj** [comment]
the version of logging installed when 'logging' is an explicit dependency (and we're not copying site packages) is from https://pypi.org/project/logging

**Comment by atsb** [comment]
Oh dear.  Ok, I'll make sure that gets fixed asap!

**Comment by atsb** [comment]
@obriencj - it is updated now in pypi

**Comment by atsb** [comment]
Only catch is due to my changes for 3.12, it means this is the new minimum version going forward.  The python team made so many breaking changes that it isn't possible to make it 3.12 compatible while also keeping 3.9/10 compatibility.

**Comment by obriencj** [comment]
Oh no. What did they break this time? That sort of thing would be a big problem, since I (and I suppose others) almost always run my unit tests on a collection of python versions (usually 3.7 - 3.11 these days). I can try and help with this if you can point me to the right general area of incompatibility.

**Comment by atsb** [comment]
Removed pkg_resources and imp.  These are the two huge ones that were used everywhere.  The only option was for me to rewrite them to importlib for 3.12

Sometimes I think the python team are just living under a rock.

**Comment by obriencj** [comment]
I agree with you, they seem kinda hateful almost.

But I've got some good news in the form of an incoming PR :)

**Comment by atsb** [comment]
> I agree with you, they seem kinda hateful almost.

Hateful, arrogant or just incompetent.  All three I'd say ;)

And thanks for the incoming PR, appreciated!

**Comment by obriencj** [comment]
I've got compatibility restored back to earlier versions. I'm actually struggling around what appears to be a bug introduced with the migration to importlib. The pypi version explodes with nested tests packages (eg.  `tests/__init__.py` `tests/something.py` `tests/foo/__init__.py` `tests/foo/bar.py` )  so I'm trying to fix that as well.

**Comment by obriencj** [comment]
I'll close this issue and open up another so we can be specific to the PR
