### ISSUE TITLE
numpy 2.0.0 drops numpy.core.unicode

### ISSUE THREAD

**Issue by obriencj** [atsb/nose-py3#19]
numpy released version 2.0.0 on the 16th. In this release, it dropped the old `numpy.core.unicode` helper.

There were only a few cases where this is imported in nose-py3, and as best I can tell they're all there for python 2 support.

I'm taking the leap to submit a PR which simply drops all numpy use and just relies on the python unicode str features.

**Comment by obriencj** [comment]
A workaround for those not wanting to wait, is to force a dependency of `numpy == 1.26`

**Comment by obriencj** [comment]
https://github.com/obriencj/koji-smoky-dingo/actions/runs/9546968603

**Comment by atsb** [comment]
I'll fix it
