### ISSUE TITLE
conflict between clr and pythonnet or ironpython package

### ISSUE THREAD

**Issue by Gerritmerecs** [atsb/nose-py3#8]
Dear maintainers of nose-py3,

i would like to know where the dependency of 'clr' comes from and if i can safely uninstall it before executing unittests with your delivered nose.plugin?
This dependency leads to issues while importing clr as this is used as a namespace by pythonnet as well.
I cannot find any usages in the nose-py3 folder of clr. 

It would be a huge help, if you could clarify this for me as i would like to use this package in replacement for nose.

Thanks in advance.
Gerrit

**Comment by atsb** [comment]
clr is a legacy dependency that is not required as far as I can see.  I have pushed a commit to master and will test it tonight on the system I use to deliver nose-py3 on.

**Comment by Gerritmerecs** [comment]
Dear atsb,
thanks for tackling the issue.
any news on your tests?
Best regards
Gerrit

**Comment by atsb** [comment]
Ahh yes, sorry!

I ran some of the functional tests without having clr as a dependency and it behaved normally.  You are free to either build from the current master (which has clr removed) or you can wait until I upload a new version to pypi.

**Comment by Gerritmerecs** [comment]
Thank you very much for your update.
I'd rather wait for your upload so i can have clean dependencies with regular updates instead of a customized build mynose-py3.
Unless you say, it'll take a month to build.

**Comment by atsb** [comment]
I'll do one today

**Comment by atsb** [comment]
It is now uploaded to pypi as 1.6.1

**Comment by Gerritmerecs** [comment]
Thank you very much for you rapid support. This works for us 🥇

**Comment by atsb** [comment]
Anytime :)
